/**
 * Signals, in the line surrounding a claim, that the document is **not**
 * claiming that path exists.
 *
 * It is the only part of the whole extractor that looks at prose, and it does
 * so in exactly one way: by searching for literal markers. It does not
 * interpret the text. The project refuses to put an LLM on the main path, so
 * the alternative to these lists is not something smarter, it is reporting the
 * false positive.
 *
 * The marker lists keep their Spanish entries alongside the English ones: these
 * run against documents written in either language, and "si existe" hedges
 * exactly as much as "if exists".
 *
 * Both classes came out of the corpus of real repos, and both are general: any
 * sufficiently long documentation writes examples and marks things as optional
 * or pending.
 */

/**
 * The path is an **example** of a convention, not a path in the repo.
 * Real case (BerriAI/litellm): "Use subdirectories that match the
 * implementation path, **such as** `auth/test_token_exchange.py` for
 * `auth/token_exchange.py`". Neither file exists, and they should not: the
 * sentence describes how to name the ones you create.
 */
const EXAMPLE = [
  'such as',
  'for example',
  'for instance',
  'e.g.',
  'eg.',
  'por ejemplo',
  'p. ej.',
  'digamos',
  'supongamos',
  'imagina',
]

/**
 * The document **hedges** about the path existing.
 * Real case (vercel/next.js): "- `turbopack/crates/README.md` (if exists)".
 * The document already says it may not be there; reporting it contradicts the
 * author.
 */
const HEDGED = [
  'if exists',
  'if it exists',
  'if present',
  'if any',
  'si existe',
  'si está',
  'si esta',
  '(optional)',
  'optional',
  'opcional',
  'not yet',
  'todavía no',
  'todavia no',
  'planned',
  'planeado',
  'coming soon',
  'proximamente',
  'próximamente',
  'deprecated',
  'obsoleto',
  // The document says the file is produced by a command. Real case
  // (vitest-dev/vitest): "`docs/.vitepress/contributor-names.json` is
  // generated by `pnpm docs:contributors`". It is neither committed nor
  // ignored: it only shows up after running the command.
  'is generated',
  'are generated',
  'generated by',
  'generated from',
  // Real case (vercel-labs/marketing-team-eve-template): "`files` entries
  // **materialize** as real siblings, so `references/ai-phrases-to-avoid.md`
  // still resolves". The file is declared in a TypeScript constant and written
  // out when the skill compiles, so it is neither committed nor ignored.
  'materialize',
  'materializes',
  'materialise',
  'materialises',
  'se genera',
  'se generan',
  'lo genera',
  'auto-generated',
  'autogenerated',
  'autogenerado',
]

/**
 * The line is an **instruction to create** something, so the path is a
 * destination and not a claim of existence.
 *
 * Real case (tursodatabase/turso): "1. Create
 * `perf/memory/src/profile/your_profile.rs` implementing the `Profile` trait".
 *
 * It only counts if the imperative opens the line, after the bullet or the step
 * number. "Create" in the middle of a sentence marks nothing; at the start of a
 * numbered step, it does. That restriction is what keeps this from suppressing
 * too much, because "add" and "create" show up everywhere in any
 * documentation.
 */
const CREATE_IMPERATIVES = [
  'create',
  'add',
  'new',
  // Real case (laravel/vet): "Write a rule in a file in `.hod/rules/`. Write a
  // skill in a directory in `.hod/skills/`." The second directory does not
  // exist because nobody has written a skill yet, which is what the sentence
  // is for.
  'write',
  // Real case (remix-run/react-router): "Save the resolved decisions to a
  // scratch file at `tasks/rfc-decisions.md`." A scratch file is written by the
  // agent following the instruction, so the path is a destination.
  'save',
  'guardar',
  'guarda',
  'escribir',
  'escribe',
  'escribí',
  'generate',
  'scaffold',
  'touch',
  'mkdir',
  'crear',
  'crea',
  'creá',
  'agregar',
  'agrega',
  'agregá',
  'añadir',
  'añade',
  'nuevo',
  'generá',
]

/** Strips bullets, step numbering and headings from the start of the line. */
function stripListMarkers(line: string): string {
  return line.replace(/^[\s>]*(?:[-*+]|#{1,6}|\d+[.)])\s*/u, '').replace(/^\*\*/u, '')
}

function isCreateInstruction(segment: string): boolean {
  // Trimmed first: a segment can open with the newline of the two-line window,
  // and `stripListMarkers` only eats leading space when a marker follows it.
  const head = stripListMarkers(segment.trimStart()).toLowerCase()
  return CREATE_IMPERATIVES.some((verb) => head.startsWith(`${verb} `))
}

/**
 * The **sentence** the claim sits in, not the whole line.
 *
 * The imperative used to be tested against the line, on the reasoning that
 * what matters is how *this* line opens. Real case (laravel/vet) showed the
 * assumption underneath it: that a line carries one claim. It carried five
 * sentences.
 *
 *     `hod` writes this file. Write no sentence in it, because `hod update`
 *     writes it again. Write the intention of the project in `.hod/PROJECT.md`.
 *     Write a rule in a file in `.hod/rules/`. Write a skill in a directory in
 *     `.hod/skills/`.
 *
 * Splitting is what keeps this from over-suppressing: the segment containing
 * the claim is the one that has to open with the verb, so "Create `a.ts`. The
 * file `b.ts` is missing." still reports `b.ts`.
 *
 * A newline is **not** a boundary, because a sentence wraps across one:
 * "Write a skill in a directory in\n`skills/mine/`." is one instruction. The
 * `false-positive-traps` fixture caught that on the first attempt, which had
 * split on newlines too.
 *
 * Terminal punctuation followed by whitespace already covers the case that
 * used to be handled line by line, since a sentence ending at the end of a
 * line matches `[.!?]\s+`.
 */
function segmentAround(text: string, claimAt: number): string {
  let start = 0
  for (const match of text.matchAll(/[.!?]\s+/gu)) {
    const end = (match.index ?? 0) + match[0].length
    if (end > claimAt) break
    start = end
  }
  const rest = text.slice(start)
  const next = /[.!?]\s/u.exec(rest)
  return next === null ? rest : rest.slice(0, next.index)
}

/**
 * The **conditional mood**: the sentence is about something that would be the
 * case, not something that is.
 *
 * Real case (spatie/bloom), a `CLAUDE.md` arguing *against* adding an Xcode
 * project to the repo:
 *
 *     XcodeGen or Tuist from a spec, or a `Tools/xcodeproj.sh` that writes one
 *     on demand, **would** avoid the merge conflicts, but the whole benefit
 *     above is a stamp Xcode writes back into `project.pbxproj`.
 *
 * `Tools/` exists with twenty-odd scripts. That one does not, and is not meant
 * to: the paragraph introduces it in order to reject it. Any sufficiently
 * thoughtful context file eventually explains why the repo is *not* organised
 * some other way, and naming the road not taken means naming paths that do not
 * exist.
 *
 * This list is the riskiest in the file, and it is deliberately scoped
 * differently from the others: it is tested against the **sentence** holding
 * the claim, never the two-line window. "would" is a word documents also write
 * about files that do exist — "you would find the config in `src/config.ts`" —
 * and over the whole window it would reach across a sentence boundary into a
 * neighbouring claim.
 *
 * It only ever costs something when a document uses a modal *and* the path is
 * genuinely stale, which is a narrower case than the word's frequency
 * suggests. Measured over the 44-repo corpus it suppressed exactly the finding
 * above and nothing else; that is evidence, not proof, and it is the reason
 * this rule was measured before being kept rather than after.
 */
const CONDITIONAL = [
  'would',
  'could',
  'might',
  'wouldn',
  'sería',
  'seria',
  'podría',
  'podria',
  'haría',
  'haria',
]

function isConditional(segment: string): boolean {
  const lower = segment.toLowerCase()
  return CONDITIONAL.some((modal) => new RegExp(`\\b${modal}\\b`, 'u').test(lower))
}

/**
 * Which prose gate closed on a claim.
 *
 * `disclaims` used to answer yes or no, which is all the extractors need: a
 * claim the prose disclaims is not emitted either way. Ticket `07` needs the
 * name, because the table it asks for is **per rule** — "`conditional`
 * suppressed forty candidates and thirty of them looked like real claims" is
 * an answer, and "the prose suppressed forty" is not.
 *
 * `EXAMPLE` and `HEDGED` are reported apart even though `proseDisclaims`
 * tests them together: they are two different arguments, and the file
 * documents them as two.
 */
export type ProseReason =
  | 'example'
  | 'hedged'
  | 'another-repo'
  | 'create-instruction'
  | 'conditional'
  | 'external-root'
  | 'creation-target'

function markerReason(lower: string): ProseReason | undefined {
  if (EXAMPLE.some((marker) => lower.includes(marker))) return 'example'
  if (HEDGED.some((marker) => lower.includes(marker))) return 'hedged'
  return undefined
}

/**
 * Whether a line **opens** an item of its own instead of continuing the
 * previous one.
 *
 * A table row, a bullet, a numbered step and a heading are independent claims.
 * A wrapped sentence, on the other hand, never starts with any of those
 * markers.
 */
function opensItsOwnItem(line: string): boolean {
  return /^[\s>]*(?:\||[-*+]\s|\d+[.)]\s|#{1,6}\s)/u.test(line)
}

/**
 * The line containing an offset, and the previous one **only if this one is its
 * continuation**.
 *
 * The line alone is not enough: a wrapped sentence splits the path's marker
 * away. Real case (BerriAI/litellm), where the "such as" ends up one line up:
 *
 *     Use subdirectories that match the implementation path, such as
 *     `auth/test_token_exchange.py` for `auth/token_exchange.py` and
 *
 * But looking at the previous line unconditionally bleeds between items that
 * have nothing to do with each other. Real case (cyanheads/git-mcp-server), two
 * rows of a table:
 *
 *     | `src/mcp-server/prompts/definitions/` | MCP Prompt definitions (e.g., ...) |
 *     | `src/mcp-server/transports/`          | Transport implementations ...      |
 *
 * The "e.g." in the first row was suppressing the second, which is a different
 * claim. That is why the window only opens when the current line does not open
 * an item of its own.
 */
type ProseWindow = {
  text: string
  /** Where the claim starts inside `text`. Locates the sentence to test. */
  claimAt: number
}

/**
 * The prose a discarded candidate sat in, for ticket `07`'s instrumentation.
 *
 * It is the **same** window `disclaimedBy` judges, deliberately: a table that
 * says "`conditional` threw this away" beside a wider or narrower excerpt than
 * the rule read would be evidence about a different rule. Exported here rather
 * than recomputed in the extractor for the same reason.
 */
export function proseWindowAround(content: string, offset: number): string {
  return lineAround(content, offset).text
}

function lineAround(content: string, offset: number): ProseWindow {
  const lineStart = content.lastIndexOf('\n', offset) + 1
  const end = content.indexOf('\n', offset)
  const lineEnd = end === -1 ? content.length : end
  const line = content.slice(lineStart, lineEnd)

  if (lineStart === 0 || opensItsOwnItem(line)) {
    return { text: line, claimAt: offset - lineStart }
  }

  const previousStart = content.lastIndexOf('\n', lineStart - 2) + 1
  return { text: content.slice(previousStart, lineEnd), claimAt: offset - previousStart }
}

/**
 * Whether the line surrounding the claim marks it as an example or leaves it
 * uncertain. The whole line is inspected, not just what comes before it: an
 * "(if exists)" arrives after the path.
 */
/**
 * A section that **roots its paths somewhere else**, so the paths under it are
 * not claims about this repo.
 *
 * Real case (mattpocock/course-video-manager), a skill documenting the API of
 * a different project:
 *
 *     ### 1. Scan API Source
 *
 *     Read the AI Hero API source at `~/repos/ai/.../ai-hero/src/`. Focus on:
 *
 *     - **REST endpoints**: `src/app/api/` — each folder is a route segment.
 *     - **tRPC routers**: `src/trpc/api/routers/`
 *     - **Database schema**: `src/db/schema.ts`
 *
 * The repo has no `src/` at all. One sentence establishes the root and four
 * bullets are written relative to it, so the existing rules see four
 * independent claims and report all four.
 *
 * `namesAnotherRepo` already covers this when the other repo is named as a
 * `github.com` URL. It does not when the root is a filesystem path, and it
 * cannot reach the following bullets in any case: it works over the two-line
 * window, and this needs the **section**.
 *
 * Two things keep the scope from swallowing whole documents:
 *
 * - The root has to be a **directory**. `~/.config/gh/hosts.yml` is a file
 *   somebody mentions in passing; only a directory is something other paths
 *   can be relative to. Without this, one mention of a dotfile in a long
 *   section would silence every real claim below it.
 * - The scope is one markdown section, heading to heading, not the document.
 */
const EXTERNAL_ROOT = /`~\/[^`\s]*\/`/u

/** Where each heading starts, plus the end of the content. */
function sectionBoundaries(content: string): number[] {
  const starts: number[] = [0]
  for (const match of content.matchAll(/^#{1,6} .*$/gmu)) {
    const start = match.index ?? 0
    if (start !== 0) starts.push(start)
  }
  starts.push(content.length)
  return starts
}

/**
 * The offset ranges of the sections that establish an external root.
 *
 * Computed once per source rather than once per claim: a document with two
 * hundred claims would otherwise rescan itself two hundred times, and the
 * end-to-end budget is 500 ms.
 */
function externalRootSections(content: string): Array<[number, number]> {
  if (!content.includes('`~/')) return []
  const bounds = sectionBoundaries(content)
  const ranges: Array<[number, number]> = []
  for (let i = 0; i + 1 < bounds.length; i += 1) {
    const start = bounds[i] ?? 0
    const end = bounds[i + 1] ?? content.length
    if (EXTERNAL_ROOT.test(content.slice(start, end))) ranges.push([start, end])
  }
  return ranges
}

function inExternalRootSection(
  ranges: ReadonlyArray<readonly [number, number]>,
  offset: number,
): boolean {
  return ranges.some(([start, end]) => offset >= start && offset < end)
}

type ProseContext = {
  /** `owner/repo` of this repo, to recognize when another one is meant. */
  origin: string | undefined
}

/**
 * Whether the line links to a repository **other** than this one.
 *
 * Real case (prisma/prisma): "`drive-*` skills and [`docs/drive/`](...) live in
 * [prisma/ignite](https://github.com/prisma/ignite) (`skills/.pilot/`)". The
 * line names another repo twice; the paths it mentions belong over there.
 *
 * With no known remote the rule does not apply: there is no way to know what
 * "another" would mean.
 */
function namesAnotherRepo(line: string, origin: string | undefined): boolean {
  if (origin === undefined) return false
  const lower = line.toLowerCase()
  for (const match of lower.matchAll(/(?:github|gitlab)\.com\/([^/\s)\]]+\/[^/\s)\]#?]+)/gu)) {
    const slug = (match[1] ?? '').replace(/\.git$/u, '')
    if (slug !== origin) return true
  }
  return false
}

function proseDisclaims(
  window: ProseWindow,
  ctx: ProseContext = { origin: undefined },
): ProseReason | undefined {
  const lower = window.text.toLowerCase()
  const marker = markerReason(lower)
  if (marker !== undefined) return marker
  if (namesAnotherRepo(window.text, ctx.origin)) return 'another-repo'
  // These two are tested against the sentence holding the claim, not the whole
  // window: see `segmentAround`. The imperative because what matters is how
  // *that* sentence opens; the conditional because it is the broadest rule
  // here and the window would carry it into a neighbouring claim.
  const sentence = segmentAround(window.text, window.claimAt)
  if (isCreateInstruction(sentence)) return 'create-instruction'
  return isConditional(sentence) ? 'conditional' : undefined
}

/**
 * The prose gates a claim has to pass, closed over one source.
 *
 * Every extractor asks the same question — "does the prose around this offset
 * disclaim a claim there?" — and three of them used to ask it in three steps,
 * each recomputing `externalRootSections` over the whole document. The steps
 * are the interesting part of this module and the sequence is not, so the
 * sequence is what it exports.
 *
 * Closing over the content is what makes the section scan happen once per
 * source instead of once per extractor: a document with two hundred claims is
 * scanned for `~/` roots once, and the end-to-end budget in `SPEC.md` § 9 is
 * 500 ms.
 */
/**
 * Every path the document **instructs the reader to create**, anywhere in it.
 *
 * `isCreateInstruction` asks whether the sentence holding the claim opens with
 * an imperative. That is the common shape and it is not the only one: a
 * document can say "Add `x`" in one bullet and refer to `x` two lines above and
 * fifty lines below, and those other mentions are about the same destination.
 *
 * Real case (remix-run/react-router), which broke ADR-0006 condition 2:
 *
 *     4. Review whether `scripts/changes/whats-changed.md` is needed:
 *        - Read `CHANGELOG.md` examples or `references/whats-changed.md` …
 *        - **Add** `scripts/changes/whats-changed.md` only for features, …
 *        - Do not add it for ordinary bug fixes …
 *
 * The two findings were on the "Review whether" line and on a "Use `…`" line
 * further down. The document spends four bullets on when to create the file, so
 * it plainly does not claim the file is there — and driftwatch offered to
 * **autofix** it into `references/whats-changed.md`, a different file the
 * document mentions one line above.
 *
 * Only backticked spans count. A path in prose without code formatting is not
 * something this project extracts as a claim either, so widening here would
 * collect strings no gate is ever asked about.
 *
 * What it costs is a document that says "Create `x`" in one place and asserts
 * `x` exists in another. That document contradicts itself, and this project
 * takes the quiet reading of a contradiction every time.
 */
function creationTargets(content: string): ReadonlySet<string> {
  const targets = new Set<string>()
  for (const line of content.split('\n')) {
    // Sentence by sentence, because one line carries several: the laravel/vet
    // case `segmentAround` was written for.
    for (const sentence of line.split(/(?<=[.!?])\s+/u)) {
      if (!isCreateInstruction(sentence)) continue
      for (const match of sentence.matchAll(/`([^`\n]+)`/gu)) {
        const value = (match[1] ?? '').trim()
        if (value !== '') targets.add(value)
      }
    }
  }
  return targets
}

export type ProseGates = {
  /**
   * The gate that says there is no claim around `offset`, or `undefined` when
   * none of them does.
   *
   * It answers with a name rather than a boolean for one reason, and it is not
   * the extractors': they only ever ask whether to emit the claim. See
   * `ProseReason`.
   */
  disclaimedBy(offset: number): ProseReason | undefined
  /**
   * Whether the document instructs the reader to create this exact path, in
   * any sentence. See `creationTargets`.
   */
  declaresDestination(text: string): boolean
}

export function proseGatesFor(content: string, origin: string | undefined): ProseGates {
  const externalRoots = externalRootSections(content)
  // Both scans are done once per source rather than once per claim: a document
  // with two hundred claims would otherwise read itself two hundred times, and
  // `SPEC.md` § 9 budgets 500 ms end to end.
  const destinations = creationTargets(content)
  return {
    declaresDestination(text) {
      return destinations.has(text)
    },
    disclaimedBy(offset) {
      // Section first, then line: the section scope is the broader answer, and
      // it is a lookup against a list computed once.
      if (inExternalRootSection(externalRoots, offset)) return 'external-root'
      return proseDisclaims(lineAround(content, offset), { origin })
    },
  }
}
