/**
 * Senales, en la linea que rodea a una afirmacion, de que el documento **no**
 * esta afirmando que esa ruta exista.
 *
 * Es lo unico de todo el extractor que mira prosa, y lo hace de una sola forma:
 * buscando marcadores literales. No interpreta el texto. El proyecto rechaza
 * meter un LLM en el camino principal, asi que la alternativa a estas listas no
 * es algo mas inteligente, es reportar el falso positivo.
 *
 * Las dos clases salieron del corpus de repos reales, y las dos son generales:
 * cualquier documentacion suficientemente larga escribe ejemplos y marca cosas
 * como opcionales o pendientes.
 */

/**
 * La ruta es un **ejemplo** de una convencion, no una ruta del repo.
 * Caso real (BerriAI/litellm): "Use subdirectories that match the
 * implementation path, **such as** `auth/test_token_exchange.py` for
 * `auth/token_exchange.py`". Ninguno de los dos archivos existe, y no deberian:
 * la frase describe como nombrar los que se creen.
 */
const EJEMPLO = [
  'such as',
  'for example',
  'for instance',
  'e.g.',
  'eg.',
  'por ejemplo',
  'p. ej.',
  'digamos',
  'supongamos',
  'imagina',
]

/**
 * El documento **se cubre** sobre la existencia de la ruta.
 * Caso real (vercel/next.js): "- `turbopack/crates/README.md` (if exists)".
 * El documento ya dice que puede no estar; reportarlo es contradecir al autor.
 */
const CUBIERTO = [
  'if exists',
  'if it exists',
  'if present',
  'if any',
  'si existe',
  'si está',
  'si esta',
  '(optional)',
  'optional',
  'opcional',
  'not yet',
  'todavía no',
  'todavia no',
  'planned',
  'planeado',
  'coming soon',
  'proximamente',
  'próximamente',
  'deprecated',
  'obsoleto',
  // El documento dice que el archivo lo produce un comando. Caso real
  // (vitest-dev/vitest): "`docs/.vitepress/contributor-names.json` is
  // generated by `pnpm docs:contributors`". No esta commiteado ni ignorado:
  // aparece recien despues de correr el comando.
  'is generated',
  'are generated',
  'generated by',
  'generated from',
  'se genera',
  'se generan',
  'lo genera',
  'auto-generated',
  'autogenerated',
  'autogenerado',
]

/**
 * La linea es una **instruccion de crear** algo, asi que la ruta es un destino
 * y no una afirmacion de existencia.
 *
 * Caso real (tursodatabase/turso): "1. Create
 * `perf/memory/src/profile/your_profile.rs` implementing the `Profile` trait".
 *
 * Solo cuenta si el imperativo abre la linea, despues de la vinieta o el
 * numero de paso. "Create" en medio de una oracion no marca nada; al principio
 * de un paso numerado, si. Esa restriccion es lo que evita suprimir de mas,
 * porque "add" y "create" aparecen por todas partes en cualquier documentacion.
 */
const IMPERATIVOS_DE_CREAR = [
  'create',
  'add',
  'new',
  'generate',
  'scaffold',
  'touch',
  'mkdir',
  'crear',
  'crea',
  'creá',
  'agregar',
  'agrega',
  'agregá',
  'añadir',
  'añade',
  'nuevo',
  'generá',
]

/** Quita vinetas, numeracion de pasos y encabezados del arranque de la linea. */
function stripListMarkers(line: string): string {
  return line.replace(/^[\s>]*(?:[-*+]|#{1,6}|\d+[.)])\s*/u, '').replace(/^\*\*/u, '')
}

function esInstruccionDeCrear(line: string): boolean {
  const head = stripListMarkers(line).toLowerCase()
  return IMPERATIVOS_DE_CREAR.some((verb) => head.startsWith(`${verb} `))
}

const MARCADORES = [...EJEMPLO, ...CUBIERTO]

/**
 * La linea que contiene un offset, mas la anterior.
 *
 * La linea sola no alcanza: una oracion envuelta parte el marcador de la ruta.
 * Caso real (BerriAI/litellm), donde el "such as" queda una linea arriba:
 *
 *     Use subdirectories that match the implementation path, such as
 *     `auth/test_token_exchange.py` for `auth/token_exchange.py` and
 *
 * Dos lineas cubren el envoltorio tipico sin tragarse un parrafo entero, que
 * suprimiria de mas.
 */
export function lineAround(content: string, offset: number): string {
  const lineStart = content.lastIndexOf('\n', offset) + 1
  const previousStart = lineStart === 0 ? 0 : content.lastIndexOf('\n', lineStart - 2) + 1
  const end = content.indexOf('\n', offset)
  return content.slice(previousStart, end === -1 ? content.length : end)
}

/**
 * Si la linea que rodea a la afirmacion la marca como ejemplo o la da por
 * incierta. Se mira la linea entera, no solo lo que va antes: un "(if exists)"
 * llega despues de la ruta.
 */
export type ProseContext = {
  /** `owner/repo` de este repo, para reconocer cuando se habla de otro. */
  origin: string | undefined
}

/**
 * Si la linea enlaza a un repositorio **distinto** de este.
 *
 * Caso real (prisma/prisma): "`drive-*` skills and [`docs/drive/`](...) live in
 * [prisma/ignite](https://github.com/prisma/ignite) (`skills/.pilot/`)". La
 * linea nombra otro repo dos veces; las rutas que menciona son de alla.
 *
 * Sin remoto conocido la regla no se aplica: no se puede saber que es "otro".
 */
function namesAnotherRepo(line: string, origin: string | undefined): boolean {
  if (origin === undefined) return false
  const lower = line.toLowerCase()
  for (const match of lower.matchAll(/(?:github|gitlab)\.com\/([^/\s)\]]+\/[^/\s)\]#?]+)/gu)) {
    const slug = (match[1] ?? '').replace(/\.git$/u, '')
    if (slug !== origin) return true
  }
  return false
}

export function proseDisclaims(line: string, ctx: ProseContext = { origin: undefined }): boolean {
  const lower = line.toLowerCase()
  if (MARCADORES.some((marker) => lower.includes(marker))) return true
  if (namesAnotherRepo(line, ctx.origin)) return true
  // El imperativo se busca por linea, no en la ventana de dos: lo que importa
  // es como abre *esta* linea.
  return line.split('\n').some(esInstruccionDeCrear)
}
